---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome
        access: default

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best
        access: default

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
        access: default
