---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: /
    access: default

- search:
    provider: duckduckgo
    target: _blank
    access: admin
